var json = [
  {
    "name": "Major Events",
    "data": [
      {
        "date": "3/6/2014 12:00:00 AM",
        "details": {
          "description": "U.S. authorizes sanctions on Russia.",
          "link": "https://www.state.gov/e/eb/tfs/spi/ukrainerussia/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/8/2015 12:00:00 AM",
        "details": {
          "description": "Rise in Russian cyberattacks.",
          "link": "https://www.thedailybeast.com/obama-to-putin-stop-hacking-me",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/16/2015 12:00:00 AM",
        "details": {
          "description": "Trump announces candidacy for president.",
          "link": "https://www.youtube.com/watch?v=apjNfkysjbM",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/4/2015 12:00:00 AM",
        "details": {
          "description": "FBI begins Clinton email investigation.",
          "link": "https://www.washingtonpost.com/politics/fbi-looks-into-security-of-clintons-private-e-mail-setup/2015/08/04/2bdd85ec-3aae-11e5-8e98-115a3cf7d7ae_story.html?utm_term=.644366284bd2",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/26/2016 12:00:00 AM",
        "details": {
          "description": "Trump clinches the GOP nomination for president.",
          "link": "http://www.npr.org/2016/05/26/479588197/donald-trump-clinches-gop-nomination",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/14/2016 12:00:00 AM",
        "details": {
          "description": "DNC announces it was hacked.",
          "link": "https://www.washingtonpost.com/world/national-security/russian-government-hackers-penetrated-dnc-stole-opposition-research-on-trump/2016/06/14/cf006cb4-316e-11e6-8ff7-7b6c1998b7a0_story.html?",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/5/2016 12:00:00 AM",
        "details": {
          "description": "Comey closes Clinton email investigation.",
          "link": "https://www.fbi.gov/news/pressrel/press-releases/statement-by-fbi-director-james-b-comey-on-the-investigation-of-secretary-hillary-clinton2019s-use-of-a-personal-e-mail-system",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/11/2016 12:00:00 AM",
        "details": {
          "description": "Trump campaign helps change GOP platform on Ukraine/Russia.",
          "link": "https://www.washingtonpost.com/opinions/global-opinions/trump-campaign-guts-gops-anti-russia-stance-on-ukraine/2016/07/18/98adb3b0-4cf3-11e6-a7d8-13d06b37f256_story.html?utm_term=.c05a2d51a711",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/15/2016 12:00:00 AM",
        "details": {
          "description": "Trump chooses Pence as VP.",
          "link": "http://www.nbcnews.com/storyline/2016-conventions/its-official-trump-announces-mike-pence-vp-pick-n610111",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/22/2016 12:00:00 AM",
        "details": {
          "description": "Wikileaks releases 20,000 DNC emails.",
          "link": "https://www.nytimes.com/2016/07/23/us/politics/dnc-emails-sanders-clinton.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/24/2016 12:00:00 AM",
        "details": {
          "description": "DNC chairwoman Debbie Wasserman Schultz resigns.",
          "link": "https://www.washingtonpost.com/politics/hacked-emails-cast-doubt-on-hopes-for-party-unity-at-democratic-convention/2016/07/24/a446c260-51a9-11e6-b7de-dfe509430c39_story.html?utm_term=.23afcd3d0254",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2016 12:00:00 AM",
        "details": {
          "description": "FBI begins investigation of DNC hack.",
          "link": "http://www.foxnews.com/politics/2016/07/25/fbi-to-investigate-dnc-email-hack.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/19/2016 12:00:00 AM",
        "details": {
          "description": "Manafort leaves Trump's campaign.",
          "link": "https://www.nytimes.com/2016/08/20/us/politics/paul-manafort-resigns-donald-trump.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/5/2016 12:00:00 AM",
        "details": {
          "description": "President Obama tells Putin to stop hacking.",
          "link": "http://www.politico.com/story/2016/12/obama-putin-232754",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/9/2016 12:00:00 AM",
        "details": {
          "description": "Second presidential debate brings up hacking.",
          "link": "https://www.washingtonpost.com/news/the-fix/wp/2016/10/09/everything-that-was-said-at-the-second-donald-trump-vs-hillary-clinton-debate-highlighted/?utm_term=.ec85042cd242",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/31/2016 12:00:00 AM",
        "details": {
          "description": "White House red phones another warning to Russia.",
          "link": "https://www.aol.com/article/news/2016/12/19/what-obama-said-to-putin-on-the-red-phone-about-the-election-hac/21631316/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/9/2017 12:00:00 AM",
        "details": {
          "description": "Trump fires Comey.",
          "link": "http://www.cnn.com/2017/05/09/politics/fbi-james-comey-fired-letter/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/1/2017 12:00:00 AM",
        "details": {
          "description": "Putin denies role in U.S. elections.",
          "link": "https://www.theatlantic.com/news/archive/2017/06/putin-russia-us-election/528825/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/8/2017 12:00:00 AM",
        "details": {
          "description": "NYT first reports Donald Trump Jr. 2016 meeting with Russian lawyer.",
          "link": "https://www.nytimes.com/2017/07/08/us/politics/trump-russia-kushner-manafort.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/11/2017 12:00:00 AM",
        "details": {
          "description": "Donald Trump Jr. releases emails about meeting with Russian lawyer after offer of anti-Hillary Clinton material.",
          "link": "https://www.nytimes.com/interactive/2017/07/11/us/politics/donald-trump-jr-email-text.html?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/27/2017 12:00:00 AM",
        "details": {
          "description": "U.S. Senate sends new Russia sanctions to Trump's desk.",
          "link": "http://www.cnn.com/2017/07/27/politics/russian-sanctions-passes-senate/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/28/2017 12:00:00 AM",
        "details": {
          "description": "Russia reacts to sanctions bill, expelling U.S. diplomats. ",
          "link": "http://www.npr.org/2017/07/30/540432397/putin-expels-755-u-s-diplomats-from-russia-in-response-to-new-sanctions-bill",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/2/2017 12:00:00 AM",
        "details": {
          "description": "Trump signs new sanctions against Russia, but says bill is \"flawed.\"",
          "link": "https://www.reuters.com/article/us-usa-trump-russia-idUSKBN1AI1Y4",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/18/2018 12:00:00 AM",
        "details": {
          "description": "Putin elected to six more years in office.",
          "link": "https://www.theguardian.com/world/2018/mar/18/vladimir-putin-wins-russian-election-with-more-than-70-of-vote-exit-poll",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/6/2018 12:00:00 AM",
        "details": {
          "description": "New U.S. sanctions against Russian oligarchs.",
          "link": "https://home.treasury.gov/news/press-releases/sm0338",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Investigations",
    "data": [
      {
        "date": "8/4/2015 12:00:00 AM",
        "details": {
          "description": "FBI begins investigating Hillary Clinton's use of a private email server while Secretary of State.",
          "link": "https://www.washingtonpost.com/politics/fbi-looks-into-security-of-clintons-private-e-mail-setup/2015/08/04/2bdd85ec-3aae-11e5-8e98-115a3cf7d7ae_story.html?utm_term=.644366284bd2",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/18/2016 12:00:00 AM",
        "details": {
          "description": "Intel director tells of attempted cyberattacks on presidential campaigns.",
          "link": "http://www.politico.com/story/2016/05/james-clapper-presidential-cyber-threats-223321",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/15/2016 12:00:00 AM",
        "details": {
          "description": "DNC's cybersecurity firm reports that Russians hacked the party's system. ",
          "link": "https://www.crowdstrike.com/blog/bears-midst-intrusion-democratic-national-committee/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/5/2016 12:00:00 AM",
        "details": {
          "description": "Comey closes Clinton email investigation.",
          "link": "https://www.fbi.gov/news/pressrel/press-releases/statement-by-fbi-director-james-b-comey-on-the-investigation-of-secretary-hillary-clinton2019s-use-of-a-personal-e-mail-system",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2016 12:00:00 AM",
        "details": {
          "description": "FBI begins investigation of DNC hack.",
          "link": "http://www.foxnews.com/politics/2016/07/25/fbi-to-investigate-dnc-email-hack.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/25/2016 12:00:00 AM",
        "details": {
          "description": "FBI receives letter from Page defending his communications.",
          "link": "https://www.washingtonpost.com/r/2010-2019/WashingtonPost/2016/09/26/Editorial-Opinion/Graphics/2016.09.25_FBI_letter.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/28/2016 12:00:00 AM",
        "details": {
          "description": "Comey reopens Clinton investigation.",
          "link": "https://www.washingtonpost.com/apps/g/page/politics/oct-28-fbi-letter-to-congressional-leaders-on-clinton-email-investigation/2113/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/6/2016 12:00:00 AM",
        "details": {
          "description": "Comey again closes Clinton investigation.",
          "link": "https://www.nytimes.com/interactive/2016/11/06/us/politics/fbi-letter-emails.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/12/2016 12:00:00 AM",
        "details": {
          "description": "Congressional Republican leaders announce they will investigate Russian attempts to disrupt the election.",
          "link": "https://www.usatoday.com/story/news/politics/elections/2016/12/12/mcconnell-says-congress-probe-russian-election-hack/95331688/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/19/2017 12:00:00 AM",
        "details": {
          "description": "Sens. Warren, Cardin ask Treasury to investigate Scaramucci-Russia Fund interaction.",
          "link": "https://www.warren.senate.gov/files/documents/2017-01-19Letter_to_Mnuchin.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/24/2017 12:00:00 AM",
        "details": {
          "description": "Flynn questioned by the FBI.",
          "link": "http://abcnews.go.com/Politics/timeline-sally-yates-warnings-white-house-mike-flynn/story?id=47272979",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/25/2017 12:00:00 AM",
        "details": {
          "description": "Acting AG Sally Yates hears about Flynn interview.",
          "link": "http://abcnews.go.com/Politics/timeline-sally-yates-warnings-white-house-mike-flynn/story?id=47272979",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/26/2017 12:00:00 AM",
        "details": {
          "description": "Yates warns White House counsel Don McGahn about Flynn.",
          "link": "http://abcnews.go.com/Politics/timeline-sally-yates-warnings-white-house-mike-flynn/story?id=47272979",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/30/2017 12:00:00 AM",
        "details": {
          "description": "Treasury Sec. Mnuchin does not say if Scaramucci violated sanctions policy.",
          "link": "https://www.warren.senate.gov/files/documents/Mnuchin_Response-20170130.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/16/2017 12:00:00 AM",
        "details": {
          "description": "The FBI interviews Papadopoulos a second time.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/1/2017 12:00:00 AM",
        "details": {
          "description": "House Intelligence Committee launches Russia investigation.",
          "link": "https://intelligence.house.gov/news/documentsingle.aspx?DocumentID=767",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/20/2017 12:00:00 AM",
        "details": {
          "description": "Comey pubicly verifies FBI investigation of Russia and Trump campaign connections.",
          "link": "https://www.washingtonpost.com/news/post-politics/wp/2017/03/20/full-transcript-fbi-director-james-comey-testifies-on-russian-interference-in-2016-election/?utm_term=.c40ec02edc84",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/21/2017 12:00:00 AM",
        "details": {
          "description": "Nunes visits White House grounds, learns about incidental surveillance of Trump associates.",
          "link": "https://www.wired.com/2017/04/devin-nunes-white-house-trump-surveillance/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/22/2017 12:00:00 AM",
        "details": {
          "description": "Nunes personally briefs president on surveillance news.",
          "link": "http://www.ajc.com/news/national/read-transcripts-rep-devin-nunes-news-conferences-about-trump-surveillance/NdZ4qQv7uBnjcH9E3HSRPJ/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/24/2017 12:00:00 AM",
        "details": {
          "description": "Nunes cancels House intelligence hearing with Yates and former intelligence heads.",
          "link": "http://www.cnn.com/2017/03/24/politics/devin-nunes-paul-manafort-house-intelligence/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/9/2017 12:00:00 AM",
        "details": {
          "description": "Trump fires Comey.",
          "link": "http://www.cnn.com/2017/05/09/politics/fbi-james-comey-fired-letter/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/14/2017 12:00:00 AM",
        "details": {
          "description": "Washington Post reports Mueller is investigating Trump for possible obstruction of justice.",
          "link": "https://www.washingtonpost.com/world/national-security/special-counsel-is-investigating-trump-for-possible-obstruction-of-justice/2017/06/14/9ce02506-5131-11e7-b064-828ba60fbb98_story.html?utm_term=.5af02ccab084",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/15/2017 12:00:00 AM",
        "details": {
          "description": "CNN: Near this date, intelligence chiefs told senators that the president asked them to deny any colllusion with Russia.",
          "link": "http://www.cnn.com/2017/06/22/politics/intel-chiefs-trump-refute-collusion/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/18/2017 12:00:00 AM",
        "details": {
          "description": "Trump attorney Jay Sekulow says he has not been told the president is under investigation for obstruction.",
          "link": "http://www.reuters.com/article/us-usa-trump-russia-idUSKBN1990O7",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/19/2017 12:00:00 AM",
        "details": {
          "description": "Following Mueller request, White House directs staff to preserve documents.",
          "link": "http://www.cnn.com/2017/07/21/politics/robert-mueller-russia-investigation-trump-tower-meeting/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/20/2017 12:00:00 AM",
        "details": {
          "description": "Report: Mueller expands investigation to include Trump business dealings.",
          "link": "https://www.bloomberg.com/news/articles/2017-07-20/mueller-is-said-to-expand-probe-to-trump-business-transactions",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2017 12:00:00 AM",
        "details": {
          "description": "Manafort meets with Senate Intelligence Committee staff, who ask about June 2016 Trump Tower meeting. ",
          "link": "https://www.nytimes.com/2017/07/25/us/politics/paul-manafort-russia-senate-intelligence-trump.html?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/26/2017 12:00:00 AM",
        "details": {
          "description": "FBI agents raid Manafort's home.",
          "link": "https://www.washingtonpost.com/politics/fbi-conducted-predawn-raid-of-former-trump-campaign-chairman-manaforts-home/2017/08/09/5879fa9c-7c45-11e7-9d08-b79f191668ed_story.html?hpid=hp_hp-top-table-high_manafort-1010am%3Ahomepage%2Fstory&amp;utm_term=.91fbde159e28",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/27/2017 12:00:00 AM",
        "details": {
          "description": "Investor Bill Browder to senators: Veselnitskaya was pushing Moscow's agenda at 2016 Trump Tower meeting.",
          "link": "http://foreignpolicy.com/2017/07/27/browder-says-no-doubt-lawyer-who-met-with-trump-jr-a-russian-agent/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/2/2017 12:00:00 AM",
        "details": {
          "description": "Trump campaign turns over 20,000 pages of documents to Senate Judiciary Committee.",
          "link": "https://www.bloomberg.com/news/articles/2017-08-08/trump-campaign-turns-over-thousands-of-documents-in-russia-probe",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/4/2017 12:00:00 AM",
        "details": {
          "description": "Donald Trump Jr. turns over 250 pages of documents to Senate Judiciary Committee.",
          "link": "https://www.bloomberg.com/news/articles/2017-08-08/trump-campaign-turns-over-thousands-of-documents-in-russia-probe",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/14/2017 12:00:00 AM",
        "details": {
          "description": "As Trump's attorney, Cohen sends letter to Congressional investigators disputing the Steele \"dossier.\"",
          "link": "http://www.foxnews.com/politics/2017/08/30/trump-attorney-delivers-point-by-point-rebuttal-totally-false-dossier.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/22/2017 12:00:00 AM",
        "details": {
          "description": "Senate Judiciary Committee daylong hearing with Fusion GPS founder.",
          "link": "http://www.pbs.org/newshour/rundown/founder-firm-tied-trump-dossier-meets-senate-committee-russia-probe/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/7/2017 12:00:00 AM",
        "details": {
          "description": "NYT report details Russian fake accounts, bots on Twitter and Facebook. ",
          "link": "https://www.nytimes.com/2017/09/07/us/politics/russia-facebook-twitter-election.html?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/13/2017 12:00:00 AM",
        "details": {
          "description": "U.S. bans government use of security software by firm connected to Russians.",
          "link": "https://www.washingtonpost.com/world/national-security/us-to-ban-use-of-kaspersky-software-in-federal-agencies-amid-concerns-of-russian-espionage/2017/09/13/36b717d0-989e-11e7-82e4-f1076f6d6152_story.html?utm_term=.8fea08da60ba",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/15/2017 12:00:00 AM",
        "details": {
          "description": "Facebook gives Mueller information on Russian ads.",
          "link": "https://www.wsj.com/articles/facebook-gave-special-counsel-robert-mueller-more-details-on-russian-ad-buys-than-congress-1505514552",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/22/2017 12:00:00 AM",
        "details": {
          "description": "DHS identifies 21 state election systems targeted by Russian hackers.",
          "link": "http://www.politico.com/story/2017/09/22/russian-hackers-election-states-targeted-dhs-243038",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/26/2017 12:00:00 AM",
        "details": {
          "description": "Roger Stone closed-door testimony on Capitol Hill. Refuses to name who worked with him and Assange.",
          "link": "http://www.politico.com/story/2017/09/25/roger-stone-testimony-congress-trump-243119",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/5/2017 12:00:00 AM",
        "details": {
          "description": "Papadopoulos signs plea agreement, guilty of lying to FBI and agreeing to cooperate.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/23/2017 12:00:00 AM",
        "details": {
          "description": "Report: Mueller investigation includes Tony Podesta, brother of Clinton campaign Chairman John Podesta, for work connected to Manafort. (NYT)",
          "link": "https://www.nbcnews.com/news/us-news/mueller-now-investigating-democratic-lobbyist-tony-podesta-n812776",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/24/2017 12:00:00 AM",
        "details": {
          "description": "WaPo publishes report that Clinton campaign paid Fusion GPS for anti-Trump research, including Steele dossier.",
          "link": "https://www.washingtonpost.com/world/national-security/clinton-campaign-dnc-paid-for-research-that-led-to-russia-dossier/2017/10/24/226fabf0-b8e4-11e7-a908-a3470754bbb9_story.html?utm_term=.50c45a0b8a32",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/30/2017 12:00:00 AM",
        "details": {
          "description": "Mueller investigation indicts Manafort and his lieutenant Rick Gates on charges related to their past work for Ukrainian politicians.",
          "link": "https://www.washingtonpost.com/world/national-security/manafort-and-former-business-partner-asked-to-surrender-in-connection-with-special-counsel-probe/2017/10/30/6fe051f0-bd67-11e7-959c-fe2b598d8c00_story.html?hpid=hp_hp-top-table-main_specialcounsel-817am-desktop%3Ahomepage%2Fstory&amp;utm_term=.33eea859431f",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/31/2017 12:00:00 AM",
        "details": {
          "description": "Twitter, Google and Facebook representatives testify before Congress on Russian meddling.",
          "link": "https://www.theguardian.com/technology/live/2017/oct/31/facebook-google-twitter-congress-russian-election-meddling-live",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/14/2017 12:00:00 AM",
        "details": {
          "description": "Sessions testifies he now recalls the 2016 Papadopolous meeting.",
          "link": "https://www.washingtonpost.com/world/national-security/sessions-likely-to-be-questioned-about-trump-campaign-dealings-with-russians-at-house-judiciary-hearing/2017/11/13/bc20b7fc-c894-11e7-aa96-54417592cf72_story.html?utm_term=.87aa41494aa5",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/16/2017 12:00:00 AM",
        "details": {
          "description": "Senate Judiciary Committee: Kushner didn't tell us about Wikileaks emails and talks for a \"backdoor\" channel with Russians.",
          "link": "https://www.washingtonpost.com/powerpost/senate-judiciary-panel-kushner-had-contacts-about-wikileaks-russian-overtures-he-did-not-disclose/2017/11/16/402586b4-cb05-11e7-8321-481fd63f174d_story.html?utm_term=.f3a4bbec6126",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/21/2017 12:00:00 AM",
        "details": {
          "description": "Mueller's team and the president's attorneys discuss the possibility of him testifying, according to letter obtained by NYT.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/30/2017 12:00:00 AM",
        "details": {
          "description": "Erik Prince testifies before House Intelligence Committee. ",
          "link": "https://www.washingtonpost.com/powerpost/erik-prince-tells-house-investigators-he-met-with-kremlin-linked-banker-in-seychelles/2017/11/30/c8a66e3e-d62e-11e7-95bf-df7c19270879_story.html?utm_term=.3a0b8be225bf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/8/2018 12:00:00 AM",
        "details": {
          "description": "Mueller's team and the president's attorneys again discuss the possibility of him testifying, according to letter obtained by NYT.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/25/2018 12:00:00 AM",
        "details": {
          "description": "White House outlines its cooperation with Mueller, points to 20+ interviews by Trump staffers.",
          "link": "https://www.washingtonpost.com/politics/russia-investigators-have-interviewed-more-than-20-white-house-officials-trumps-legal-team-says/2018/01/25/5a4f587a-01e8-11e8-8acf-ad2991367d9d_story.html?utm_term=.1b944858a7fc",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/29/2018 12:00:00 AM",
        "details": {
          "description": "Trump attorney John Dowd drafts letter to Mueller arguing that the president has the power to shut down investigations and that, because of such powers, his actions could never be obstruction of justice.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/2/2018 12:00:00 AM",
        "details": {
          "description": "House Intelligence Republicans release once-classified memo accusing FBI of bias.",
          "link": "https://assets.documentcloud.org/documents/4365340/Read-the-GOP-memo.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/22/2018 12:00:00 AM",
        "details": {
          "description": "Mueller's team brings a second indictment, with 32 counts of tax and bank fraud, against Paul Manafort and Rick Gates.",
          "link": "https://www.justice.gov/file/1038391/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/24/2018 12:00:00 AM",
        "details": {
          "description": "House Intelligence Democrats release a counter-memo on the FBI.",
          "link": "https://www.npr.org/2018/02/24/588563076/memo-by-house-intelligence-committee-democrats-released-as-nunes-addresses-cpac",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/28/2018 12:00:00 AM",
        "details": {
          "description": "DOJ inspector general launches investigation of FBI, DOJ and possible abuse of FISA/surveillance powers, including with the Carter Page wiretaps.",
          "link": "http://www.foxnews.com/politics/2018/03/28/doj-inspector-general-investigates-alleged-fisa-abuses-by-doj-fbi.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/4/2018 12:00:00 AM",
        "details": {
          "description": "Sen. Intelligence Committee interviews Felix Sater, who worked on Russia deals with Trump.",
          "link": "https://www.buzzfeed.com/emmaloop/senate-investigators-interview-a-former-trump-business?utm_term=.ssKv06QEPv#.bmNy39QKky",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/27/2018 12:00:00 AM",
        "details": {
          "description": "House Intelligence Committee releases separate final reports from GOP and Dems. Republicans conclude no evidence of collusion.",
          "link": "https://intelligence.house.gov/news/documentsingle.aspx?DocumentID=882",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/17/2018 12:00:00 AM",
        "details": {
          "description": "Reuters report: Manafort's ex-son-in-law Jeffrey Yohai agreed to a plea deal in real estate case, may have to cooperate with Mueller.",
          "link": "https://www.reuters.com/article/us-usa-trump-russia-manafort-exclusive/exclusive-manaforts-former-son-in-law-cuts-plea-deal-to-cooperate-with-government-sources-idUSKCN1II2YM",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Russians, Hacking",
    "data": [
      {
        "date": "3/15/2015 12:00:00 AM",
        "details": {
          "description": "CNN reports the State Deptartment suspects Russians are behind a continuing, nearly yearlong and \"worst ever\" hack.",
          "link": "http://www.cnn.com/2015/03/10/politics/state-department-hack-worst-ever/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/8/2015 12:00:00 AM",
        "details": {
          "description": "U.S. cybersecurity expert says he is seeing dramatic rise in cyber aggression from Russia.",
          "link": "https://www.thedailybeast.com/obama-to-putin-stop-hacking-me",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/23/2015 12:00:00 AM",
        "details": {
          "description": "DOD secretary Ashton Carter reveals suspected Russian hack of Pentagon.",
          "link": "http://www.cnn.com/2015/04/23/politics/russian-hackers-pentagon-network/index.html/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2015 12:00:00 AM",
        "details": {
          "description": "Russians launch cyberattack against the Pentagon's Joint Staff email system. Officials shut it down temporarily.",
          "link": "https://www.cnbc.com/2015/08/06/russia-hacks-pentagon-computers-nbc-citing-sources.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/15/2015 12:00:00 AM",
        "details": {
          "description": "The @Ten_GOP twitter account is created. It's purported to be the Tennessee Republicans but is later reported to be Russian trolls. It pushes support of Michael Flynn, allegations of vote fraud and gets dozens of RT's from Trump campaign staffers.",
          "link": "https://www.thedailybeast.com/trump-campaign-staffers-pushed-russian-propaganda-days-before-the-election",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/19/2016 12:00:00 AM",
        "details": {
          "description": "Clinton campaign chair John Podesta opens a phishing email sent by Russian hackers.",
          "link": "https://www.nytimes.com/2016/12/13/us/politics/russia-hack-election-dnc.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/22/2016 12:00:00 AM",
        "details": {
          "description": "Another Clinton staffer falls for phishing scam.",
          "link": "https://www.nytimes.com/2016/12/13/us/politics/russia-hack-election-dnc.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/26/2016 12:00:00 AM",
        "details": {
          "description": "The \"professor\" tells Trump advisor Papadopoulos that Russians have \"thousands\" of Hillary Clinton emails.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/14/2016 12:00:00 AM",
        "details": {
          "description": "DNC announces it was hacked.",
          "link": "https://www.washingtonpost.com/world/national-security/russian-government-hackers-penetrated-dnc-stole-opposition-research-on-trump/2016/06/14/cf006cb4-316e-11e6-8ff7-7b6c1998b7a0_story.html?",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/15/2016 12:00:00 AM",
        "details": {
          "description": "Guccifer 2.0 claims DNC hack, leaks report on Trump.",
          "link": "http://www.thesmokinggun.com/documents/crime/dnc-hacker-leaks-trump-oppo-report-647293",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/21/2016 12:00:00 AM",
        "details": {
          "description": "Guccifer 2.0 leaks DNC hack documents about Clinton.",
          "link": "https://guccifer2.wordpress.com/2016/06/21/hillary-clinton/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/22/2016 12:00:00 AM",
        "details": {
          "description": "Wikileaks releases 20,000 DNC emails.",
          "link": "https://www.nytimes.com/2016/07/23/us/politics/dnc-emails-sanders-clinton.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/12/2016 12:00:00 AM",
        "details": {
          "description": "Hackers release cell phone numbers, personal information and other documents about Democratic members of Congress.",
          "link": "https://www.nytimes.com/2016/08/13/us/politics/democratic-party-documents-hack.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/24/2016 12:00:00 AM",
        "details": {
          "description": "Russian hackers targeted U.S. voting software company, according to NSA.",
          "link": "https://theintercept.com/2017/06/05/top-secret-nsa-report-details-russian-hacking-effort-days-before-2016-election/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/11/2016 12:00:00 AM",
        "details": {
          "description": "Obama admin. warns Russia to stop hacking.",
          "link": "https://www.wsj.com/articles/white-house-vows-proportional-response-for-russian-dnc-hack-1476220192",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/31/2016 12:00:00 AM",
        "details": {
          "description": "Hackers use stolen logins to send cyberattack emails to 122 local voting officials.",
          "link": "https://theintercept.com/2017/06/05/top-secret-nsa-report-details-russian-hacking-effort-days-before-2016-election/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/7/2017 12:00:00 AM",
        "details": {
          "description": "Wikileaks releases CIA documents.",
          "link": "https://wikileaks.org/ciav7p1/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/1/2017 12:00:00 AM",
        "details": {
          "description": "Putin denies role in U.S. elections, suggests \"patriotic hackers\" outside government may be behind hack.",
          "link": "https://www.theatlantic.com/news/archive/2017/06/putin-russia-us-election/528825/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/22/2017 12:00:00 AM",
        "details": {
          "description": "Russia denies using Facebook to try to influence the election.",
          "link": "https://www.reuters.com/article/us-usa-trump-russia-facebook/kremlin-russia-did-not-use-facebook-adverts-to-sway-u-s-election-idUSKCN1BX109",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/17/2017 12:00:00 AM",
        "details": {
          "description": "Report: Russian trolling operation likely cost $2.3 million, reached 6 million people.",
          "link": "http://www.rbc.ru/technology_and_media/17/10/2017/59e4eb7a9a79472577375776",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Trump",
    "data": [
      {
        "date": "10/17/2013 12:00:00 AM",
        "details": {
          "description": "Trump tells David Letterman: \"I've done a lot of business with the Russians.\"",
          "link": "https://www.youtube.com/watch?v=PR_SoJpWzOA",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/9/2013 12:00:00 AM",
        "details": {
          "description": "Trump holds Miss Universe (which he owns) in Moscow, meets Russian entrepreneurs.",
          "link": "https://www.bloomberg.com/news/articles/2016-12-21/the-day-trump-came-to-moscow-oligarchs-miss-universe-and-nobu",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/10/2013 12:00:00 AM",
        "details": {
          "description": "Trump tweets that U.S. must be strategic with Russia.",
          "link": "https://twitter.com/realDonaldTrump/status/399729261684490240",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/16/2015 12:00:00 AM",
        "details": {
          "description": "Trump announces candidacy for president.",
          "link": "https://www.youtube.com/watch?v=apjNfkysjbM",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/17/2015 12:00:00 AM",
        "details": {
          "description": "Trump and Putin praise each other, saying in separate statements they want better relations.",
          "link": "https://www.yahoo.com/news/putin-says-welcomes-trumps-calls-deeper-ties-russia-123323669.html?ref=gs",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/31/2016 12:00:00 AM",
        "details": {
          "description": "Trump meets with his national security team, including Sessions and Papadopoulos. The latter says he could arrange a meeting with Putin.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/27/2016 12:00:00 AM",
        "details": {
          "description": "Trump meets Russian ambassador Sergey Kislyak.",
          "link": "http://www.independent.co.uk/news/world/americas/us-politics/donald-trump-russian-ambassador-sergey-kislyak-meeting-election-campaign-a7617261.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/10/2016 12:00:00 AM",
        "details": {
          "description": "Russian magnate Aras Agalarov delivers an \"expensive painting\" to Trump for his birthday.",
          "link": "https://docs.house.gov/meetings/IG/IG00/20180322/108023/HRPT-115-2.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/15/2016 12:00:00 AM",
        "details": {
          "description": "Trump accuses DNC of being behind the hack of their system.",
          "link": "http://www.politico.com/story/2016/06/donald-trump-opposition-224397",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/17/2016 12:00:00 AM",
        "details": {
          "description": "Trump writes effusive thank you note to Agalarov for the painting.",
          "link": "https://docs.house.gov/meetings/IG/IG00/20180322/108023/HRPT-115-2.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/21/2016 12:00:00 AM",
        "details": {
          "description": "Trump fires campaign manager Corey Lewandowski, Manafort takes over.",
          "link": "http://www.foxnews.com/politics/2016/06/21/canning-corey-why-trump-firing-lewandowski-could-shift-his-campaign.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/24/2016 12:00:00 AM",
        "details": {
          "description": "Trump gives NYC speech focused on his criticism of Hillary Clinton. It's unclear if this is what he was signaling June 7.",
          "link": "http://www.politico.com/story/2016/06/transcript-trump-speech-on-the-stakes-of-the-election-224654",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/27/2016 12:00:00 AM",
        "details": {
          "description": "Trump says he hopes Russia finds missing Clinton emails.",
          "link": "http://www.cnbc.com/2016/07/27/trump-hope-russia-finds-the-30000-emails-that-are-missing.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/31/2016 12:00:00 AM",
        "details": {
          "description": "Trump: Crimea prefers Russia.",
          "link": "http://abcnews.go.com/ThisWeek/trump-crimeas-people-prefer-russia-elected-putin-ukraine/story?id=41029437",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/8/2016 12:00:00 AM",
        "details": {
          "description": "Trump to Russian TV: Russia interference \"pretty unlikely.\"",
          "link": "http://www.politico.com/story/2016/09/trump-johnson-stein-have-no-chance-of-winning-227922",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/13/2016 12:00:00 AM",
        "details": {
          "description": "Russia formally complains to U.N. about criticism of Trump, others.",
          "link": "https://apnews.com/161afebf5804419b93f7c6306d438cc1/apnewsbreak-un-criticism-trump-prompts-russian-response",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/24/2016 12:00:00 AM",
        "details": {
          "description": "Trump team says Page made \"no contribution\" to the campaign.",
          "link": "http://thehill.com/homenews/campaign/297599-trump-campaign-backs-away-from-adviser-suspected-of-ties-to-kremlin",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/19/2016 12:00:00 AM",
        "details": {
          "description": "Trump doubts U.S. intel on Russia.",
          "link": "http://www.nbcnews.com/politics/first-read/trump-has-been-strikingly-consistent-denying-russian-hacking-role-n703866",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/31/2016 12:00:00 AM",
        "details": {
          "description": "Trump praises Comey for reopening Clinton email probe.",
          "link": "https://www.theguardian.com/us-news/video/2016/oct/31/donald-trump-fbi-james-comey-congress-video",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/28/2016 12:00:00 AM",
        "details": {
          "description": "Trump, named Time's 2016 person of the year, tells the magazine, \"I do not believe Russia interfered.\"",
          "link": "http://time.com/4591183/time-person-of-the-year-2016-donald-trump-interview/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/15/2016 12:00:00 AM",
        "details": {
          "description": "Putin sends Trump a letter asking to restore U.S.-Russia relationship.",
          "link": "http://www.politico.com/story/2016/12/putin-christmas-letter-to-trump-232952",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/22/2017 12:00:00 AM",
        "details": {
          "description": "Trump calls Comey over to shake hands during a White House reception.",
          "link": "http://www.latimes.com/nation/politics/trailguide/la-na-trailguide-updates-at-white-house-reception-a-pat-on-the-1485128431-htmlstory.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/30/2017 12:00:00 AM",
        "details": {
          "description": "Trump fires Yates for ordering DOJ not to defend the president's travel ban.",
          "link": "http://fortune.com/video/2017/03/29/president-trump-fires-acting-attorney-general-sally-yates/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/1/2017 12:00:00 AM",
        "details": {
          "description": "NYT: Trump instructs top WH lawyer to stop Sessions from recusing himself in the Russia investigation.",
          "link": "https://www.nytimes.com/2018/01/04/us/politics/trump-sessions-russia-mcgahn.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/5/2017 12:00:00 AM",
        "details": {
          "description": "Comey asks DOJ to publicly deny Trump's wiretap charge.",
          "link": "https://www.nytimes.com/2017/03/05/us/politics/trump-seeks-inquiry-into-allegations-that-obama-tapped-his-phones.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/20/2017 12:00:00 AM",
        "details": {
          "description": "On or near this date,Trump reportedly asks intelligence chiefs to deny coordination between Russia and his campaign.",
          "link": "https://www.washingtonpost.com/world/national-security/trump-asked-intelligence-chiefs-to-push-back-against-fbi-collusion-probe-after-comey-revealed-its-existence/2017/05/22/394933bc-3f10-11e7-9869-bac8b446820a_story.html?utm_term=.32ddafabf76f",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/22/2017 12:00:00 AM",
        "details": {
          "description": "Trump reportedly asks Director of National Intelligence Daniel Coats to get Comey to back off investigation into Flynn.",
          "link": "https://www.washingtonpost.com/world/national-security/top-intelligence-official-told-associates-trump-asked-him-if-he-could-intervene-with-comey-to-get-fbi-to-back-off-flynn/2017/06/06/cc879f14-4ace-11e7-9669-250d0b15f83b_story.html?hpid=hp_hp-top-table-main_usrussia-810pm%3Ahomepage%2Fstory&amp;utm_term=.209bc4e9a4f0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/30/2017 12:00:00 AM",
        "details": {
          "description": "Comey says Trump called him at the FBI and,  describing the Russia investigation as a \"cloud,\" asked Comey to publicly say the president was not under investigation.",
          "link": "https://www.intelligence.senate.gov/sites/default/files/documents/os-jcomey-060817.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/2/2017 12:00:00 AM",
        "details": {
          "description": "Trump calls Comey a \"phony,\" tweeting the FBI director \"was the best thing that ever happened to Hillary Clinton.\"",
          "link": "https://twitter.com/realDonaldTrump/status/859601184285491201",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/8/2017 12:00:00 AM",
        "details": {
          "description": "Trump tweets that story about campaign collusion with Russia is a \"total hoax.\"",
          "link": "https://twitter.com/realDonaldTrump/status/861713823505494016",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/9/2017 12:00:00 AM",
        "details": {
          "description": "Trump fires Comey.",
          "link": "http://www.cnn.com/2017/05/09/politics/fbi-james-comey-fired-letter/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/23/2017 12:00:00 AM",
        "details": {
          "description": "Trump retains adviser Marc Kasowitz as his private attorney for Russia probe.",
          "link": "http://www.reuters.com/article/us-usa-trump-russia-counsel-idUSKBN18J30W",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/12/2017 12:00:00 AM",
        "details": {
          "description": "Trump tweets that obstruction of justice allegations are part of a \"witch hunt.\"",
          "link": "https://twitter.com/realDonaldTrump/status/875321478849363968",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/14/2017 12:00:00 AM",
        "details": {
          "description": "WaPo, NYT: Near this date, Trump ordered that Mueller be fired, but relented after White House counsel Don McGahn threatened to quit.",
          "link": "https://www.nytimes.com/2018/01/25/us/politics/trump-mueller-special-counsel-russia.html?hp&amp;action=click&amp;pgtype=Homepage&amp;clickSource=story-heading&amp;module=span-ab-top-region&amp;region=top-news&amp;WT.nav=top-news",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/15/2017 12:00:00 AM",
        "details": {
          "description": "New York Times reports Trump transition team orders former staff to keep all documents related to Russia or Ukraine.",
          "link": "https://www.nytimes.com/2017/06/16/us/politics/trump-transition-team-russia-inquiry.html?rref=collection%2Fsectioncollection%2Fpolitics&amp;action=click&amp;contentCollection=politics&amp;region=rank&amp;module=package&amp;version=highlights&amp;contentPlacement=2&amp;pgtype=sectionfront&amp;_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/16/2017 12:00:00 AM",
        "details": {
          "description": "Trump tweets that he is being investigated \"for firing the FBI director by the man who told me to fire the FBI director.\"",
          "link": "https://twitter.com/realDonaldTrump/status/875701471999864833",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/18/2017 12:00:00 AM",
        "details": {
          "description": "Trump again tweets the investigation is a \"witch hunt.\"",
          "link": "https://twitter.com/realDonaldTrump/status/876388733607694336?ref_src=twsrc%5Etfw&amp;ref_url=http%3A%2F%2Fwww.pbs.org%2Fnewshour%2Frundown%2Ftrump-frustration-with-russia-investigation%2F",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/20/2017 12:00:00 AM",
        "details": {
          "description": "Spicer says he does not know if Trump believes the Russians tried to meddle in the election.",
          "link": "http://time.com/4826069/sean-spicer-donald-trump-russian-interference-2016-election/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/22/2017 12:00:00 AM",
        "details": {
          "description": "In a FOX News interview, the president implies he may not want Mueller in the job. ",
          "link": "http://www.businessinsider.com/trump-fox-news-today-russia-investigation-robert-mueller-james-comey-2017-6",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/22/2017 12:00:00 AM",
        "details": {
          "description": "Trump admits he does not have Oval Office tapes of Comey conversation.",
          "link": "https://www.theguardian.com/us-news/2017/jun/22/trump-conversations-comey-fbi-tapes",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/23/2017 12:00:00 AM",
        "details": {
          "description": "The president acknowledges \"Russian meddling\" in a tweet, accuses Obama of doing nothing.",
          "link": "https://twitter.com/realDonaldTrump/status/878413313188802560?ref_src=twsrc%5Etfw&amp;ref_url=http%3A%2F%2Fwww.newsweek.com%2Fdonald-trump-russia-election-hacking-barack-obama-hillary-clinton-628835",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/11/2017 12:00:00 AM",
        "details": {
          "description": "NYT reports Trump signed off on his son's statement about meeting with Russian lawyer.",
          "link": "https://www.nytimes.com/2017/07/11/us/politics/russia-trump.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/12/2017 12:00:00 AM",
        "details": {
          "description": "Trump attorney says POTUS not involved in drafting his son's statement about Russia meeting.",
          "link": "http://www.cnn.com/2017/08/01/politics/timeline-donald-trump-jr-/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/16/2017 12:00:00 AM",
        "details": {
          "description": "President Trump's attorney again denies POTUS had role in Trump Jr. statement.",
          "link": "http://www.nbcnews.com/feature/meet-the-press-24-7/meet-press-july-16-2017-n783491",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/17/2017 12:00:00 AM",
        "details": {
          "description": "Trump praises son for releasing Russia meeting emails.",
          "link": "https://twitter.com/realDonaldTrump/status/886950594220568576",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/19/2017 12:00:00 AM",
        "details": {
          "description": "To NYT, Trump criticizes Sessions for recusing himself from Russia investigation.",
          "link": "https://www.nytimes.com/2017/07/19/us/politics/trump-interview-transcript.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2017 12:00:00 AM",
        "details": {
          "description": "Trump tells Wall Street Journal he's \"just looking at\" firing Sessions.",
          "link": "https://blogs.wsj.com/washwire/2017/07/25/donald-trumps-interview-with-the-wall-street-journal-edited-transcript/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/1/2017 12:00:00 AM",
        "details": {
          "description": "White House says Trump did weigh in on son's statement to NYT.",
          "link": "http://www.cnn.com/2017/08/01/politics/trump-russia-meeting-statement/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/1/2017 12:00:00 AM",
        "details": {
          "description": "Trump misses the Oct. 1 deadline to impose new, required sanctions against Russia.",
          "link": "https://www.mccain.senate.gov/public/index.cfm/2017/10/senators-mccain-cardin-question-administration-delay-in-russia-sanctions-implementation",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/30/2017 12:00:00 AM",
        "details": {
          "description": "Trump tweets that events in Manafort indictment occurred before he was in the campaign and that there was no collusion.",
          "link": "https://twitter.com/realDonaldTrump/status/925005659569041409",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/11/2017 12:00:00 AM",
        "details": {
          "description": "At an Asian summit,Trump says Putin again privately assured him \"he didn't meddle.\"",
          "link": "https://www.nytimes.com/2017/11/11/world/asia/trump-putin-election.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/12/2017 12:00:00 AM",
        "details": {
          "description": "Trump tells reporters he accepts U.S. intel over Putin on meddling, saying \"I'm with our agencies.\"",
          "link": "https://apnews.com/6a54a956998740f98997fc6461f7d132",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/21/2017 12:00:00 AM",
        "details": {
          "description": "Mueller's team and the president's attorneys discuss the possibility of him testifying, according to letter obtained by NYT.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/8/2018 12:00:00 AM",
        "details": {
          "description": "Mueller's team and the president's attorneys again discuss the possibility of him testifying, according to letter obtained by NYT.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/29/2018 12:00:00 AM",
        "details": {
          "description": "Trump attorney John Dowd drafts letter to Mueller arguing that the president has the power to shut down investigations and that, because of such powers, his actions could never be obstruction of justice.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/17/2018 12:00:00 AM",
        "details": {
          "description": "Trump's personal lawyer, John Dowd, said he hopes Deputy Attorney General Rosenstein shuts down the Mueller investigation.",
          "link": "https://www.thedailybeast.com/trumps-lawyer-its-time-to-fire-robert-mueller",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/20/2018 12:00:00 AM",
        "details": {
          "description": "Trump congratulates Putin on re-election, despite staff warning \"do not congratulate.\"",
          "link": "https://www.nytimes.com/2018/03/20/us/politics/trump-putin-russia.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/22/2018 12:00:00 AM",
        "details": {
          "description": "John Dowd, Trump's attorney for the Mueller investigation, resigns. ",
          "link": "https://www.nytimes.com/2018/03/22/us/politics/john-dowd-resigns-trump-lawyer.html?smid=tw-nytpolitics&amp;smtyp=cur",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/16/2018 12:00:00 AM",
        "details": {
          "description": "Trump halts plan for possible new economic sanctions on Russia.",
          "link": "https://www.washingtonpost.com/politics/trump-puts-the-brake-on-new-russian-sanctions-reversing-haleys-announcement/2018/04/16/ac3ad4f8-417f-11e8-8569-26fda6b404c7_story.html?utm_term=.d397825bdc3b",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/26/2018 12:00:00 AM",
        "details": {
          "description": "Trump rails against DOJ, FBI and Mueller in FOX interview. Also confirms Cohen worked for him  but was a \"tiny, tiny fraction\" of his legal work.",
          "link": "https://www.washingtonpost.com/news/the-fix/wp/2018/04/26/trumps-unwieldy-fox-and-friends-interview-annotated/?utm_term=.afb1c97d1923",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/2/2018 12:00:00 AM",
        "details": {
          "description": "White House announces lead Russia probe lawyer Ty Cobb is leaving, will be replaced by Emmet Flood.",
          "link": "https://www.nytimes.com/2018/03/22/us/politics/john-dowd-resigns-trump-lawyer.html?smid=tw-nytpolitics&amp;smtyp=cur",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/20/2018 12:00:00 AM",
        "details": {
          "description": "Trump demands DOJ investigate whether DOJ or the FBI spied on his campaign for political purposes.  ",
          "link": "https://twitter.com/realDonaldTrump/status/998256454590193665",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/30/2018 12:00:00 AM",
        "details": {
          "description": "Trump tweets he wished he had picked someone other than Sessions as attorney general.",
          "link": "https://twitter.com/realDonaldTrump/status/1001807216297627648?tfw_site=NPR&amp;ref_src=twsrc%5Etfw&amp;ref_url=https%3A%2F%2Fwww.npr.org%2F2018%2F05%2F30%2F615435491%2Ftrump-i-wish-i-did-pick-a-different-attorney-general-than-sessions",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/31/2018 12:00:00 AM",
        "details": {
          "description": "Trump tweets that he \"never fired James Comey because of Russia.\"",
          "link": "https://twitter.com/realDonaldTrump/status/1002160516733853696",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/2/2018 12:00:00 AM",
        "details": {
          "description": "The NYT publishes Jan. letter by Trump's attorney asserting obstruction of justice charges could not apply to the president. The letter also indicates Trump dictated the statement by his son, Donald Trump Jr., about the 2016 Trump Tower/Russian lawyer meeting.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/4/2018 12:00:00 AM",
        "details": {
          "description": "Trump tweets that he has the right to pardon himself and that the appointment of Mueller is unconstitutional.",
          "link": "https://twitter.com/realDonaldTrump/status/1003616210922147841?ref_src=twsrc%5Etfw&amp;ref_url=https%3A%2F%2Fwww.politico.com%2Fstory%2F2018%2F06%2F04%2Ftrump-pardon-tweet-620658",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Cohen",
    "data": [
      {
        "date": "5/27/2013 12:00:00 AM",
        "details": {
          "description": "Cohen tells Page Six that Trump is considering presidential run, spent $1 million on research.",
          "link": "https://pagesix.com/2013/05/27/trump-researching-2016-run/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/19/2016 12:00:00 AM",
        "details": {
          "description": "Christopher Steele writes in his dossier that a Kremlin insider told him \"the importance of Trump lawyer Cohen in the ongoing secret liaison with the Kremlin,\" and that Cohen's role had grown.",
          "link": "https://www.documentcloud.org/documents/3259984-Trump-Intelligence-Allegations.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/20/2017 12:00:00 AM",
        "details": {
          "description": "Cohen meets with Russian oligarch Viktor Vekselberg at inauguration, according to NYT.",
          "link": "https://www.nytimes.com/2018/05/08/us/politics/michael-cohen-shell-company-payments.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/6/2017 12:00:00 AM",
        "details": {
          "description": "A pro-Russia peace plan that would lift sanctions is hand-delivered to Flynn at the White House, according to the NYT. The White House later denied receiving the plan.",
          "link": "https://www.nytimes.com/2017/02/19/us/politics/donald-trump-ukraine-russia.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/14/2017 12:00:00 AM",
        "details": {
          "description": "Trump atty Michael Cohen sends letter to Congressional investigators disputing the \"dossier\" made public in January.",
          "link": "http://www.foxnews.com/politics/2017/08/30/trump-attorney-delivers-point-by-point-rebuttal-totally-false-dossier.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/9/2018 12:00:00 AM",
        "details": {
          "description": "The FBI raids Cohen's home, office and hotel room, seizing records. Reports indicate he is under investigation for campaign finance, bank fraud.",
          "link": "https://www.washingtonpost.com/politics/fbi-seizes-records-related-to-stormy-daniels-in-raid-of-trump-attorney-michael-cohens-office/2018/04/09/e3e43cf4-3c30-11e8-974f-aacd97698cef_story.html?utm_term=.c17a420ad00a",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/25/2018 12:00:00 AM",
        "details": {
          "description": "Cohen asserts his Fifth Amendment right not to testify in the Stephanie Clifford (aka Stormy Daniels) case.",
          "link": "https://www.cnn.com/2018/04/25/politics/michael-cohen-fifth-amendment/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/26/2018 12:00:00 AM",
        "details": {
          "description": "Trump tells Fox News that Cohen handled a \"tiny, tiny fraction\" of his legal work.",
          "link": "https://www.washingtonpost.com/news/the-fix/wp/2018/04/26/trumps-unwieldy-fox-and-friends-interview-annotated/?utm_term=.afb1c97d1923",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Manafort and Gates",
    "data": [
      {
        "date": "11/21/2013 12:00:00 AM",
        "details": {
          "description": "In Ukraine, Yanukovych abruptly breaks with EU and embraces billions in aid from Moscow, contrary to Manafort's advice.",
          "link": "http://www.reuters.com/article/us-ukraine-crisis-timeline/timeline-political-crisis-in-ukraine-and-russias-occupation-of-crimea-idUSBREA270PO20140308",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/29/2016 12:00:00 AM",
        "details": {
          "description": "Manafort sends written pitch to Trump to work on the campaign.",
          "link": "https://www.nytimes.com/2017/04/08/us/to-charm-trump-paul-manafort-sold-himself-as-an-affordable-outsider.html?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/28/2016 12:00:00 AM",
        "details": {
          "description": "Manafort hired by Trump campaign.",
          "link": "https://www.nytimes.com/politics/first-draft/2016/03/28/donald-trump-hires-paul-manafort-to-lead-delegate-effort/?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/5/2016 12:00:00 AM",
        "details": {
          "description": "Near this date, Manafort meets with former Ukraine associate and Russian Army veteran Konstantin Kilimnik.",
          "link": "https://www.washingtonpost.com/politics/at-height-of-russia-tensions-trump-campaign-chairman-manafort-met-with-business-associate-from-ukraine/2017/06/18/6ab8485c-4c5d-11e7-a186-60c031eab644_story.html?utm_term=.17ee9dbfba73",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/19/2016 12:00:00 AM",
        "details": {
          "description": "Manafort becomes campaign chairman.",
          "link": "https://www.washingtonpost.com/news/post-politics/wp/2016/05/19/veteran-strategist-paul-manafort-becomes-trumps-campaign-chairman/?utm_term=.04c454a69d84",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/9/2016 12:00:00 AM",
        "details": {
          "description": "As result of June 3 email, Russian lawyer meets at Trump Tower with Donald Trump. Jr, Kushner, Manafort and other Russians. Trump Jr. says the lawyer gave no information on Clinton or anything campaign-related",
          "link": "https://www.nytimes.com/interactive/2017/07/18/us/politics/donald-trump-jr-russia-meeting.html?rref=collection%2Ftimestopic%2FTrump%2C%20Donald%20J%20Jr&amp;action=click&amp;contentCollection=timestopics&amp;region=stream&amp;module=stream_unit&amp;version=latest&amp;contentPlacement=1&amp;pgtype=collection",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/21/2016 12:00:00 AM",
        "details": {
          "description": "Manafort takes over running Trump's campaign.",
          "link": "https://www.bostonglobe.com/news/politics/2016/06/20/donald-trump-tries-hit-reset-firing-campaign-manager-corey-lewandowski/YhHxHfGM3E9WFz0rWpvwEP/story.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/7/2016 12:00:00 AM",
        "details": {
          "description": "Manafort writes in an email that he is willing to brief a VIP believed to be Russian oligarch Oleg Deripaska, according to WaPo. It's unclear if the briefings happened.",
          "link": "https://www.washingtonpost.com/politics/manafort-offered-to-give-russian-billionaire-private-briefings-on-2016-campaign/2017/09/20/399bba1a-9d48-11e7-8ea1-ed975285475e_story.html?utm_term=.a6ab7e9f276a",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/15/2016 12:00:00 AM",
        "details": {
          "description": "Manafort strongly denies taking any \"off-books\" cash for work in Ukraine.",
          "link": "http://www.politico.eu/article/manafort-blasts-nyt-denies-he-accepted-ukraine-cash-payments-donald-trump/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/19/2016 12:00:00 AM",
        "details": {
          "description": "Manafort resigns as Trump's campaign chair.",
          "link": "https://www.nytimes.com/2016/08/20/us/politics/paul-manafort-resigns-donald-trump.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/19/2016 12:00:00 AM",
        "details": {
          "description": "Christopher Steele writes in his dossier that a Kremlin insider told him Manafort had led efforts for a secret Trump-campaign relationship with Russians, until his ouster.",
          "link": "https://www.documentcloud.org/documents/3259984-Trump-Intelligence-Allegations.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/10/2016 12:00:00 AM",
        "details": {
          "description": "Manafort tells CBS News that the Ukrainian government concluded the \"Black Ledger\" was falsified.",
          "link": "https://www.kyivpost.com/ukraine-politics/manafort-claims-ukrainian-government-proven-black-ledger-falsified.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/21/2016 12:00:00 AM",
        "details": {
          "description": "Manafort's son-in-law's real estate company declares bankruptcy, documents millions owed to Manafort.",
          "link": "http://bankrupt.com/misc/cacb16-15157.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/20/2017 12:00:00 AM",
        "details": {
          "description": "Spicer says Manafort had a \"very limited role\" in the campaign. Politifact later rates that statement as false.",
          "link": "http://www.politifact.com/truth-o-meter/statements/2017/mar/22/sean-spicer/sean-spicers-false-claim-paul-manafort-played-mino/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/22/2017 12:00:00 AM",
        "details": {
          "description": "Ukrainian journalist and Manafort critic releases 2009 receipt showing payment to Manafort for computer equipment. The critic says it is a cover for laundering. Manafort allies say it is a fake document.",
          "link": "http://www.cnn.com/2017/03/21/politics/paul-manafort-ukraine/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/14/2017 12:00:00 AM",
        "details": {
          "description": "Report: NY attorney general and Manhattan's district attorney have opened investigations into Manafort real estate transactions.",
          "link": "https://www.bloomberg.com/news/articles/2017-05-14/manafort-s-real-estate-deals-said-to-be-probed-by-n-y-s-top-cop",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/26/2017 12:00:00 AM",
        "details": {
          "description": "NYT: Around this date, Putin ally and ex-Manafort associate Oleg Deripaska asks for immunity deal with Congres, but no deal is made.",
          "link": "https://www.nytimes.com/2017/05/26/us/politics/oleg-deripaska-paul-manafort.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/19/2017 12:00:00 AM",
        "details": {
          "description": "Manafort associate Konstantin Kilimnik tells Washington Post he has no relation to Russian intelligence. Others insist he *was* connected.",
          "link": "https://www.washingtonpost.com/politics/at-height-of-russia-tensions-trump-campaign-chairman-manafort-met-with-business-associate-from-ukraine/2017/06/18/6ab8485c-4c5d-11e7-a186-60c031eab644_story.html?utm_term=.17ee9dbfba73",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/27/2017 12:00:00 AM",
        "details": {
          "description": "Manafort registers retroactively as a foreign agent for his previous work in Urkaine.",
          "link": "http://www.npr.org/2017/06/28/534765010/paul-manaforts-firm-received-17-1-million-from-ukrainian-political-party",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/19/2017 12:00:00 AM",
        "details": {
          "description": "NYT reports Manafort owed millions to pro-Russia interests. Manafort spokesman says those debts are not current.",
          "link": "https://www.nytimes.com/2017/07/19/us/politics/paul-manafort-russia-trump.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2017 12:00:00 AM",
        "details": {
          "description": "Manafort answers questions from Senate Intelligence Committee staff about 2016 meeting with Russian lawyer.",
          "link": "https://www.nytimes.com/2017/07/25/us/politics/paul-manafort-russia-senate-intelligence-trump.html?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/26/2017 12:00:00 AM",
        "details": {
          "description": "The FBI raids Manafort's home in Virginia.",
          "link": "https://www.nytimes.com/2017/09/18/us/politics/mueller-russia-investigation.html?mcubz=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/2/2017 12:00:00 AM",
        "details": {
          "description": "Manafort turns over about 400 pages of documents to Senate Judiciary Committee.",
          "link": "https://www.bloomberg.com/news/articles/2017-08-08/trump-campaign-turns-over-thousands-of-documents-in-russia-probe",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/23/2017 12:00:00 AM",
        "details": {
          "description": "NBC News reports Mueller is now investigating Tony Podesta, brother of Clinton campaign Chairman John Podesta, for previous work regarding Ukraine that was connected to Manafort.",
          "link": "https://www.nbcnews.com/news/us-news/mueller-now-investigating-democratic-lobbyist-tony-podesta-n812776",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/30/2017 12:00:00 AM",
        "details": {
          "description": "Manafort and his deputy, Rick Gates, are charged with a combined 12 counts of financial and foreign agent crimes.  They both plead not guilty. Manafort spokesman issues a sharp statement.",
          "link": "https://www.washingtonpost.com/world/national-security/manafort-and-former-business-partner-asked-to-surrender-in-connection-with-special-counsel-probe/2017/10/30/6fe051f0-bd67-11e7-959c-fe2b598d8c00_story.html?hpid=hp_hp-top-table-main_specialcounsel-817am-desktop%3Ahomepage%2Fstory&amp;utm_term=.33eea859431f",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/22/2018 12:00:00 AM",
        "details": {
          "description": "Mueller's team brings a second indictment, with 32 counts of tax and bank fraud, against Paul Manafort and Rick Gates.",
          "link": "https://www.justice.gov/file/1038391/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/17/2018 12:00:00 AM",
        "details": {
          "description": "Reuters reports that Manafort's ex-son-in-law Jeffrey Yohai agreed to a plea deal in a real estate case and may have to cooperate in Mueller probe.",
          "link": "https://www.reuters.com/article/us-usa-trump-russia-manafort-exclusive/exclusive-manaforts-former-son-in-law-cuts-plea-deal-to-cooperate-with-government-sources-idUSKCN1II2YM",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/4/2018 12:00:00 AM",
        "details": {
          "description": "Prosecutors with Mueller's team filed court documents accusing Manafort of trying to tamper with witnesses in his case.",
          "link": "https://assets.documentcloud.org/documents/4493887/Mueller-motion-accusing-Paul-Manafort-of-witness.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Kushner",
    "data": [
      {
        "date": "6/9/2016 12:00:00 AM",
        "details": {
          "description": "As result of June 3 email, Russian lawyer meets at Trump Tower with Donald Trump. Jr, Kushner, Manafort and other Russians. Trump Jr. says the lawyer gave no information on Clinton or anything campaign-related",
          "link": "https://www.nytimes.com/interactive/2017/07/18/us/politics/donald-trump-jr-russia-meeting.html?rref=collection%2Ftimestopic%2FTrump%2C%20Donald%20J%20Jr&amp;action=click&amp;contentCollection=timestopics&amp;region=stream&amp;module=stream_unit&amp;version=latest&amp;contentPlacement=1&amp;pgtype=collection",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/21/2017 12:00:00 AM",
        "details": {
          "description": "Kushner submits a third security clearance form, amending it to include June 2016 meeting.",
          "link": "https://www.yahoo.com/amphtml/news/sources-trump-lawyers-knew-russia-emails-back-june-000320831.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/24/2017 12:00:00 AM",
        "details": {
          "description": "Kushner releases statement about Russia meetings, asserts his innocence and meets privately with Senate committee staff.",
          "link": "https://www.nytimes.com/2017/07/24/us/politics/jared-kushner-russia-senate.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2017 12:00:00 AM",
        "details": {
          "description": "Kushner speaks privately with House Intelligence committee.",
          "link": "http://www.reuters.com/article/us-usa-trump-russia-kushner-idUSKBN1AA2BU",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/16/2017 12:00:00 AM",
        "details": {
          "description": "Senate Judiciary Committee charges that Kushner did not disclose talks for a \"backdoor\" channel with Russians and emails about Wikileaks.",
          "link": "https://www.washingtonpost.com/powerpost/senate-judiciary-panel-kushner-had-contacts-about-wikileaks-russian-overtures-he-did-not-disclose/2017/11/16/402586b4-cb05-11e7-8321-481fd63f174d_story.html?utm_term=.f3a4bbec6126",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Trump Jr.",
    "data": [
      {
        "date": "6/3/2016 12:00:00 AM",
        "details": {
          "description": "In email chain, Donald Trump Jr. agrees to meet with Russian officials, says \"I love it\" to their offer to damage Hillary Clinton.",
          "link": "https://www.nytimes.com/interactive/2017/07/11/us/politics/donald-trump-jr-email-text.html?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/9/2016 12:00:00 AM",
        "details": {
          "description": "As result of June 3 email, Russian lawyer meets at Trump Tower with Donald Trump. Jr, Kushner, Manafort and other Russians. Trump Jr. says the lawyer gave no information on Clinton or anything campaign-related",
          "link": "https://www.nytimes.com/interactive/2017/07/18/us/politics/donald-trump-jr-russia-meeting.html?rref=collection%2Ftimestopic%2FTrump%2C%20Donald%20J%20Jr&amp;action=click&amp;contentCollection=timestopics&amp;region=stream&amp;module=stream_unit&amp;version=latest&amp;contentPlacement=1&amp;pgtype=collection",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/24/2016 12:00:00 AM",
        "details": {
          "description": "Donald Trump Jr. disputes Democratic claims about Russian hacking.",
          "link": "http://transcripts.cnn.com/TRANSCRIPTS/1607/24/sotu.01.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/21/2016 12:00:00 AM",
        "details": {
          "description": "Donald Trump Jr.reponds to a direct Twitter message from Wikileaks -- his first of three.",
          "link": "https://twitter.com/DonaldJTrumpJr/status/930228239494209536",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/1/2016 12:00:00 AM",
        "details": {
          "description": "Donald Trump Jr. retweets a voter fraud allegation from the @Ten_GOP account later blocked by Twitter and reportedly run by Russian trolls.",
          "link": "https://www.thedailybeast.com/trump-campaign-staffers-pushed-russian-propaganda-days-before-the-election",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/9/2017 12:00:00 AM",
        "details": {
          "description": "Donald Trump Jr. releases statement about meeting with Russian lawyer.",
          "link": "https://www.cnbc.com/2017/07/09/donald-trump-jr-full-statement-on-meeting-with-a-russian-lawyer.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/11/2017 12:00:00 AM",
        "details": {
          "description": "Donald Trump Jr. releases emails about meeting with Russian lawyer after offer of anti-Hillary Clinton material.",
          "link": "https://www.nytimes.com/interactive/2017/07/11/us/politics/donald-trump-jr-email-text.html?_r=0",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/30/2017 12:00:00 AM",
        "details": {
          "description": "Over this weekend, incoming White House Chief of Staff John Kelly reportedly tells Sessions his job is safe.",
          "link": "https://www.bloomberg.com/news/articles/2017-08-03/kelly-is-said-to-assure-sessions-he-can-stay-as-attorney-general",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/4/2018 12:00:00 AM",
        "details": {
          "description": "Reps. Mark Meadows and Jim Jordan write in an op-ed that it's time for Sessions to go.",
          "link": "https://www.washingtonexaminer.com/reps-mark-meadows-and-jim-jordan-its-time-for-jeff-sessions-to-go-as-shown-by-the-latest-fbi-leak",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/2/2018 12:00:00 AM",
        "details": {
          "description": "The NYT publishes Jan. letter by Trump's attorney asserting obstruction of justice charges could not apply to the president. The letter also indicates Trump dictated the statement by his son, Donald Trump Jr., about the 2016 Trump Tower/Russian lawyer meeting.",
          "link": "https://www.nytimes.com/interactive/2018/06/02/us/politics/trump-legal-documents.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Flynn",
    "data": [
      {
        "date": "12/2/2015 12:00:00 AM",
        "details": {
          "description": "Flynn and his son meet with Russian ambassador Kislyak, seemingly at Flynn's request.",
          "link": "https://intelligence.house.gov/uploadedfiles/final_russia_investigation_report.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/26/2016 12:00:00 AM",
        "details": {
          "description": "Flynn is a Trump adviser.",
          "link": "http://www.reuters.com/article/us-usa-election-trump-advisor-idUSMTZSAPEC2Q6G3JRH",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/9/2016 12:00:00 AM",
        "details": {
          "description": "Flynn signs $600,000 contract to lobby for firm tied to Turkish government.",
          "link": "http://www.politico.com/story/2017/04/25/michael-flynn-turkey-russia-237550",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/25/2016 12:00:00 AM",
        "details": {
          "description": "Flynn texts \"Merry Christmas\" to Kislyak.",
          "link": "http://www.cnn.com/TRANSCRIPTS/1701/13/cnr.05.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/24/2017 12:00:00 AM",
        "details": {
          "description": "Flynn questioned by the FBI.",
          "link": "http://abcnews.go.com/Politics/timeline-sally-yates-warnings-white-house-mike-flynn/story?id=47272979",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/26/2017 12:00:00 AM",
        "details": {
          "description": "White House learns Flynn misled Pence about his conversations with the Russians.",
          "link": "http://abcnews.go.com/Politics/timeline-sally-yates-warnings-white-house-mike-flynn/story?id=47272979",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/30/2017 12:00:00 AM",
        "details": {
          "description": "Yates invites McGahn to DOJ to review Flynn files; it's unclear whether he came.",
          "link": "http://abcnews.go.com/Politics/timeline-sally-yates-warnings-white-house-mike-flynn/story?id=47272979",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/6/2017 12:00:00 AM",
        "details": {
          "description": "A pro-Russia peace plan that would lift sanctions is hand-delivered to Flynn at the White House, according to the NYT. The White House later denied receiving the plan.",
          "link": "https://www.nytimes.com/2017/02/19/us/politics/donald-trump-ukraine-russia.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/11/2017 12:00:00 AM",
        "details": {
          "description": "Flynn files financial disclosure form without citing Russian payments for speeches.",
          "link": "http://www.foxnews.com/politics/2017/04/02/flynn-initially-failed-to-disclose-russia-linked-payments-on-ethics-form.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/30/2017 12:00:00 AM",
        "details": {
          "description": "Reports: Flynn offered to testify to FBI, House, Senate in exchange for immunity. None took him up on the offer.",
          "link": "https://www.wsj.com/articles/mike-flynn-offers-to-testify-in-exchange-for-immunity-1490912959",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/5/2017 12:00:00 AM",
        "details": {
          "description": "In Russian TV interview, Kislyak insists he and Flynn never talked about sanctions, though reports indicated otherwise.",
          "link": "https://www.usatoday.com/story/news/2017/08/05/former-russian-ambassador-sergey-kislyak-denies-discussing-secrets-sanctions-mike-flynn/542311001/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/1/2017 12:00:00 AM",
        "details": {
          "description": "Flynn pleads guilty to lying to the FBI, indicating he will cooperate with Mueller.",
          "link": "https://www.pbs.org/newshour/politics/michael-flynn-charged-with-making-false-statements-to-fbi",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Papadopolous",
    "data": [
      {
        "date": "3/6/2016 12:00:00 AM",
        "details": {
          "description": "According to Papadopolous, a Trump \"campaign supervisor,\" later identified as Sam Clovis, told him the campaign had a foreign policy goal of U.S.-Russia relations. Clovis' lawyer disputed that.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/14/2016 12:00:00 AM",
        "details": {
          "description": "In Italy, Papadopoulos meets \"the professor,\" who claims to be close with Russian officials.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/21/2016 12:00:00 AM",
        "details": {
          "description": "Trump says Papadopoulos is on his campaign team.",
          "link": "http://www.politico.com/blogs/2016-gop-primary-live-updates-and-results/2016/03/trump-foreign-policy-team-221049",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/24/2016 12:00:00 AM",
        "details": {
          "description": "In London, the \"professor\" introduces Papadopoulos to a \"native Russian female\" contact, supposedly a Putin relative. Papadopolous emails his campaign supervisor, who responds \"great work.\"",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/31/2016 12:00:00 AM",
        "details": {
          "description": "Trump meets with his natl security team, including Sessions and Papadopolous. The latter says he could arrange a meeting w/ Putin.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/18/2016 12:00:00 AM",
        "details": {
          "description": "The \"professor\" introduces Papadopoulos to a person said to be connected to the Russian foreign ministry.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/22/2016 12:00:00 AM",
        "details": {
          "description": "Papadopoulos and his foreign ministry contact exchange more emails.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/25/2016 12:00:00 AM",
        "details": {
          "description": "Papadopoulos emails a senior campaign advisor indicating the Russians are ready to meet with Trump.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/26/2016 12:00:00 AM",
        "details": {
          "description": "The \"professor\" tells Papadopoulos that Russians have \"thousands\" of Hillary Clinton emails.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/27/2016 12:00:00 AM",
        "details": {
          "description": "Papadopoulos emails a senior campaign advisor that he has some interesting messages from Moscow.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/4/2016 12:00:00 AM",
        "details": {
          "description": "Russian foreign ministry contact emails Papadopoulos about a possible meeting in Moscow.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/21/2016 12:00:00 AM",
        "details": {
          "description": "Papadopoulos emails another high-ranking campaign official about the idea of a Trump meeting with Russia.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/1/2016 12:00:00 AM",
        "details": {
          "description": "Papadopoulos emails a high-ranking campaign official and then his campaign supervisor about a Trump meeting with Russian officials.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/19/2016 12:00:00 AM",
        "details": {
          "description": "Papadopoulos writes the high-ranking campaign official that Russians would meet with him, off record, instead of Trump, if Trump is not an option.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/15/2016 12:00:00 AM",
        "details": {
          "description": "Papadopoulos' campaign supervisor writes to encourage him to attend an off-record trip to Russia, \"if feasible.\"",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/16/2017 12:00:00 AM",
        "details": {
          "description": "The FBI interviews Papadopoulos a second time.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/17/2017 12:00:00 AM",
        "details": {
          "description": "Papadopolous deactives a Facebook account that contained some information about his contact with the \"professor.\" His new account does not contain that information.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/27/2017 12:00:00 AM",
        "details": {
          "description": "Papadopoulos is arrested upon arrival at Dulles Airport outside of Washington.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/5/2017 12:00:00 AM",
        "details": {
          "description": "Papadopoulos signs plea agreement, stating he lied to the FBI in past interviews and indicating he is a cooperating witness.",
          "link": "https://www.justice.gov/file/1007346/download",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/30/2017 12:00:00 AM",
        "details": {
          "description": "Mueller unseals Papadopoulos' Oct. 5 plea agreement, detailing Russia and campaign contacts.",
          "link": "https://www.washingtonpost.com/world/national-security/manafort-and-former-business-partner-asked-to-surrender-in-connection-with-special-counsel-probe/2017/10/30/6fe051f0-bd67-11e7-959c-fe2b598d8c00_story.html?hpid=hp_hp-top-table-main_specialcounsel-817am-desktop%3Ahomepage%2Fstory&amp;utm_term=.33eea859431f",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Page",
    "data": [
      {
        "date": "3/21/2016 12:00:00 AM",
        "details": {
          "description": "Trump says Carter Page is on his campaign team.",
          "link": "http://www.politico.com/blogs/2016-gop-primary-live-updates-and-results/2016/03/trump-foreign-policy-team-221049",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/7/2016 12:00:00 AM",
        "details": {
          "description": "Page gives a lecture in Moscow.",
          "link": "https://www.youtube.com/watch?v=1CYF29saA9w",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/15/2016 12:00:00 AM",
        "details": {
          "description": "Around this time, an FBI informant meets Page at a conference.",
          "link": "https://www.nytimes.com/2018/05/18/us/politics/trump-fbi-informant-russia-investigation.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/5/2016 12:00:00 AM",
        "details": {
          "description": "Trump campaign: Page is informal adviser.",
          "link": "https://www.washingtonpost.com/business/economy/trump-advisers-public-comments-ties-to-moscow-stir-unease-in-both-parties/2016/08/05/2e8722fa-5815-11e6-9aee-8075993d73a2_story.html?utm_term=.fdc7992907f6",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/24/2016 12:00:00 AM",
        "details": {
          "description": "Trump team denies Page's role in campaign.",
          "link": "http://thehill.com/homenews/campaign/297599-trump-campaign-backs-away-from-adviser-suspected-of-ties-to-kremlin",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/25/2016 12:00:00 AM",
        "details": {
          "description": "Page writes to FBI, saying he didn't meet with any \"sanctioned\" Russians.",
          "link": "https://www.washingtonpost.com/r/2010-2019/WashingtonPost/2016/09/26/Editorial-Opinion/Graphics/2016.09.25_FBI_letter.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/26/2016 12:00:00 AM",
        "details": {
          "description": "Page denies meeting Russians, takes leave from campaign.",
          "link": "https://www.washingtonpost.com/news/josh-rogin/wp/2016/09/26/trumps-russia-adviser-speaks-out-calls-accusations-complete-garbage/?utm_term=.275f36978095",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "12/8/2016 12:00:00 AM",
        "details": {
          "description": "Page travels to Moscow.",
          "link": "https://www.nytimes.com/2016/12/08/world/europe/carter-page-donald-trump-moscow-russia.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/17/2017 12:00:00 AM",
        "details": {
          "description": "Page tells PBS NewsHour he had no Russian meetings in the last year.",
          "link": "http://www.pbs.org/newshour/bb/former-trump-adviser-says-no-russian-meetings-last-year/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/2/2017 12:00:00 AM",
        "details": {
          "description": "Page testifies behind closed doors before House Intelligence Committee, which later releases a transcript.",
          "link": "https://intelligence.house.gov/uploadedfiles/carter_page_hpsci_hearing_transcript_nov_2_2017.pdf",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/28/2018 12:00:00 AM",
        "details": {
          "description": "DOJ inspector general launches investigation of FBI, DOJ and possible abuse of FISA/surveillance powers, including with the Carter Page wiretaps.",
          "link": "http://www.foxnews.com/politics/2018/03/28/doj-inspector-general-investigates-alleged-fisa-abuses-by-doj-fbi.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  },
  {
    "name": "Sessions, Stone, and Other",
    "data": [
      {
        "date": "8/8/2015 12:00:00 AM",
        "details": {
          "description": "Stone leaves Trump campaign.",
          "link": "http://www.cnn.com/2015/08/08/politics/donald-trump-campaign-roger-stone/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/21/2015 12:00:00 AM",
        "details": {
          "description": "Jeff Sessions, then a senator, appears at Trump rally wearing a 'Make America Great Again' hat.",
          "link": "https://www.washingtonpost.com/news/politics/wp/2017/03/02/what-jeff-sessions-said-about-russia-and-when/?utm_term=.0476d9887ad8",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "2/28/2016 12:00:00 AM",
        "details": {
          "description": "Sessions formally endorses Trump.",
          "link": "http://www.politico.com/story/2016/02/sen-jeff-sessions-endorses-trump-219939",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/3/2016 12:00:00 AM",
        "details": {
          "description": "Sessions becomes chairman of the Trump campaign's national security advisory team.",
          "link": "http://www.cnn.com/2016/03/03/politics/donald-trump-jeff-sessions-national-security/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/17/2016 12:00:00 AM",
        "details": {
          "description": "The Trump campaign says Sessions will also lead Trump's foreign policy advisory team.",
          "link": "http://www.breitbart.com/big-government/2016/03/17/trump-campaign-releases-new-details-about-sessions-role-as-foreign-policy-adviser/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/27/2016 12:00:00 AM",
        "details": {
          "description": "Sessions may have met with Kislyak.",
          "link": "http://www.cnn.com/2017/05/31/politics/congress-investigating-jeff-sessions-russian-ambassador-meeting/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/23/2016 12:00:00 AM",
        "details": {
          "description": "Trump campaign signs contract with Cambridge Analytica, according to the Wall Street Journal.",
          "link": "https://www.wsj.com/articles/data-firms-wikileaks-outreach-came-as-it-joined-trump-campaign-1510339346",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/24/2016 12:00:00 AM",
        "details": {
          "description": "DNC Chair Debbie Wasserman-Schultz resigns.",
          "link": "https://www.theatlantic.com/news/archive/2016/07/dnc-wasserman-schultz-resigns/492836/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/5/2016 12:00:00 AM",
        "details": {
          "description": "Roger Stone writes that Guccifer 2.0, not Russia, is responsible for hack.",
          "link": "http://www.breitbart.com/2016-presidential-race/2016/08/05/dear-hillary-dnc-hack-solved-so-now-stop-blaming-russia/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/8/2016 12:00:00 AM",
        "details": {
          "description": "Stone says he has communicated with Wikileaks' Julian Assange.",
          "link": "https://www.mediamatters.org/video/2016/08/09/roger-stone-confirms-hes-communication-julian-assange/212261",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "8/21/2016 12:00:00 AM",
        "details": {
          "description": "Stone tweets Podesta's \"time\" is coming.",
          "link": "https://twitter.com/RogerJStoneJr/status/767366825743097856",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "9/8/2016 12:00:00 AM",
        "details": {
          "description": "Sessions meets with Kislyak.",
          "link": "http://www.foxnews.com/politics/2017/03/02/sessions-provides-details-on-meetings-with-russian-ambassador.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/2/2016 12:00:00 AM",
        "details": {
          "description": "Stone tweets \"Wednesday @HillaryClinton is done. #Wikileaks.\"",
          "link": "https://twitter.com/rogerjstonejr/status/782443074874138624?lang=en",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/3/2016 12:00:00 AM",
        "details": {
          "description": "Stone indicates more coming from Wikileaks.",
          "link": "https://twitter.com/RogerJStoneJr/status/782994854964031489",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/4/2016 12:00:00 AM",
        "details": {
          "description": "Assange promises new Wikileaks info every week.",
          "link": "http://www.foxnews.com/politics/2016/10/04/wikileaks-to-publish-presidential-election-docs-every-week-for-next-10-weeks.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/11/2016 12:00:00 AM",
        "details": {
          "description": "Podesta: Trump campaign is connected to hackers.",
          "link": "https://www.washingtonpost.com/news/the-fix/wp/2016/10/12/is-there-actually-evidence-that-trump-allies-had-a-heads-up-on-what-wikileaks-was-doing/?utm_term=.413606796331",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/12/2016 12:00:00 AM",
        "details": {
          "description": "Stone: I have back channel to Assange.",
          "link": "http://miami.cbslocal.com/2016/10/12/trump-ally-roger-stone-admits-back-channel-tie-to-wikileaks/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/14/2016 12:00:00 AM",
        "details": {
          "description": "Pence: The Trump campaign is not in cahoots with Wikipedia.",
          "link": "https://www.politico.com/story/2016/10/mike-pence-denies-trump-wikileaks-229786",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/27/2016 12:00:00 AM",
        "details": {
          "description": "Bloomberg report details Trump's digital strategy, including near total reliance on Facebook ads and data.",
          "link": "https://www.bloomberg.com/news/articles/2016-10-27/inside-the-trump-bunker-with-12-days-to-go",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/6/2016 12:00:00 AM",
        "details": {
          "description": "Trump campaign manager Kellyanne Conway retweets @Ten_GOP account later blocked by Twitter and reportedly run by Russian trolls.",
          "link": "https://www.thedailybeast.com/trump-campaign-staffers-pushed-russian-propaganda-days-before-the-election",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/16/2017 12:00:00 AM",
        "details": {
          "description": "Trump transition aide Anthony Scaramucci, hedge fund CEO, meets with Kirill Dmitriev of the Russian Direct Investment Fund in Davos. Length of meeting unclear. RDIF was under sanctions at time. ",
          "link": "https://www.bloomberg.com/news/articles/2017-01-17/in-davos-trump-aide-talks-deals-with-sanctioned-kremlin-fund",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "1/20/2017 12:00:00 AM",
        "details": {
          "description": "Russian tycoon and Putin ally Viktor Vekselberg attends Trump's inauguration, according to WaPo. The NYT reported he was the guest of his cousin and RNC donor Andrew Intrater and met with Michael Cohen.",
          "link": "https://www.washingtonpost.com/politics/amid-trumps-inaugural-festivities-members-of-russias-elite-anticipated-a-thaw-between-moscow-and-washington/2018/01/20/0d767f46-fb9f-11e7-ad8c-ecbb62019393_story.html?utm_term=.f24fb9e978af",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/1/2017 12:00:00 AM",
        "details": {
          "description": "Sessions comes under fire for not disclosing two meetings with Kislyak.",
          "link": "https://www.washingtonpost.com/world/national-security/sessions-spoke-twice-with-russian-ambassador-during-trumps-presidential-campaign-justice-officials-say/2017/03/01/77205eda-feac-11e6-99b4-9e613afeb09f_story.html?utm_term=.565f9c001335",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/2/2017 12:00:00 AM",
        "details": {
          "description": "Sessions recuses himself from any Russia investigations.",
          "link": "https://www.theguardian.com/us-news/2017/mar/02/jeff-sessions-calls-for-resignation-claims-lies-russia",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/6/2017 12:00:00 AM",
        "details": {
          "description": "Sessions writes letter clarifying Senate testimony about contact with Russians.",
          "link": "https://www.washingtonpost.com/news/post-nation/wp/2017/03/06/sessions-updates-testimony-to-congress-insists-he-was-correct-to-say-he-had-no-communication-with-russians-in-campaign/?utm_term=.642fc8bb13b6",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/20/2017 12:00:00 AM",
        "details": {
          "description": "Sens. Patrick Leahy, D-Vt., and Al Franken, D-Minn., ask Comey to investigate whether Sessions perjured himself.",
          "link": "http://www.cnn.com/2017/06/01/politics/sessions-russian-ambassador-letter/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/28/2017 12:00:00 AM",
        "details": {
          "description": "Sessions tells 'Today' show he is also recusing himself from any investigation of Flynn.",
          "link": "http://www.politico.com/story/2017/04/28/jeff-sessions-recusal-michael-flynn-investigation-237736",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/8/2017 12:00:00 AM",
        "details": {
          "description": "Deputy Attorney General Rod Rosenstein drafts a memo making a case for firing Comey, but only after he has been told that Comey is to be fired. It is not clear who directed him to write the memo.",
          "link": "https://www.washingtonpost.com/powerpost/rosenstein-heads-back-to-capitol-hill-friday-to-brief-house-members/2017/05/19/e205b3f8-3c8c-11e7-9e48-c4f199710b69_story.html?utm_term=.4942da405a6e",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/12/2017 12:00:00 AM",
        "details": {
          "description": "Trump confidant Christopher Ruddy, CEO of Newsmax Media, tells NewsHour he thinks the president is \"considering perhaps terminating\" Mueller.",
          "link": "http://www.pbs.org/newshour/rundown/trump-confidant-think-hes-considering-perhaps-terminating-special-counsel/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/15/2017 12:00:00 AM",
        "details": {
          "description": "Pence hires a private attorney to represent him in the Russia investigation.",
          "link": "http://www.cnbc.com/2017/06/15/vice-president-pence-hires-outside-counsel-to-deal-with-russia-inquiries-wapo.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/16/2017 12:00:00 AM",
        "details": {
          "description": "Trump's personal attorney, Michael Cohen, hires his own attorney to represent him in Russia probe.",
          "link": "https://www.washingtonpost.com/news/post-politics/wp/2017/06/16/trumps-personal-lawyer-michael-cohen-hires-his-own-lawyer-in-russia-probe/?utm_term=.34ea53aa2172",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/25/2017 12:00:00 AM",
        "details": {
          "description": "Russian Ambassador Kislyak is recalled to Moscow.",
          "link": "https://www.buzzfeed.com/johnhudson/moscow-is-finally-recalling-russian-ambassador-sergey?utm_term=.daeeM9o0m#.afPbR5oO9",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/19/2017 12:00:00 AM",
        "details": {
          "description": "To NYT, Trump criticizes Sessions for recusing himself from Russia investigation.",
          "link": "https://www.nytimes.com/2017/07/19/us/politics/trump-interview-transcript.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/20/2017 12:00:00 AM",
        "details": {
          "description": "Sessions says he will serve \"as long as appropriate.\"",
          "link": "http://www.npr.org/2017/07/20/538303658/sessions-says-he-plans-to-continue-serving-as-attorney-general",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/21/2017 12:00:00 AM",
        "details": {
          "description": "Anthony Scaramucci announced as new White House communications director.",
          "link": "https://www.usatoday.com/story/news/politics/onpolitics/2017/07/21/anthony-scaramucci-considered-for-white-house-communications-director/498833001/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/25/2017 12:00:00 AM",
        "details": {
          "description": "Trump tells Wall Street Journal he's \"just looking at\" firing Sessions.",
          "link": "https://blogs.wsj.com/washwire/2017/07/25/donald-trumps-interview-with-the-wall-street-journal-edited-transcript/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/28/2017 12:00:00 AM",
        "details": {
          "description": "Russia's RT news runs story in which Veselnitskaya insists Broward lied to Senate and he is behind a smear campaign.",
          "link": "https://www.rt.com/usa/397705-russia-probe-veselnitskaya-browder-us/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/30/2017 12:00:00 AM",
        "details": {
          "description": "Over this weekend, incoming White House Chief of Staff John Kelly reportedly tells Sessions his job is safe.",
          "link": "https://www.bloomberg.com/news/articles/2017-08-03/kelly-is-said-to-assure-sessions-he-can-stay-as-attorney-general",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "7/31/2017 12:00:00 AM",
        "details": {
          "description": "Scaramucci fired as White House communications director.",
          "link": "https://www.nytimes.com/2017/07/31/us/politics/trump-white-house-obamacare-health.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "10/18/2017 12:00:00 AM",
        "details": {
          "description": "Sessions testifies before Senate, again insists he never colluded with Russians.",
          "link": "http://www.cnn.com/2017/10/18/politics/jeff-sessions-senate-testimony/index.html",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "11/14/2017 12:00:00 AM",
        "details": {
          "description": "Sessions tells House committee he now recalls the March 2016 meeting in which Papadopolous relayed he was in contact with Russians. Sessions says he does not recall exactly what Papadopolous said.",
          "link": "https://www.washingtonpost.com/world/national-security/sessions-likely-to-be-questioned-about-trump-campaign-dealings-with-russians-at-house-judiciary-hearing/2017/11/13/bc20b7fc-c894-11e7-aa96-54417592cf72_story.html?utm_term=.87aa41494aa5",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "3/16/2018 12:00:00 AM",
        "details": {
          "description": "FBI deputy director Andrew McCabe is fired, officially due to actions connected to the Clinton investigation. McCabe asserted he was fired because of the Russia investigation.",
          "link": "https://www.theatlantic.com/politics/archive/2018/03/presidential-target-andrew-mccabe-was-just-fired-from-the-fbi/555857/",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/6/2018 12:00:00 AM",
        "details": {
          "description": "U.S. newly sanctions seven Russian oligarchs including Oleg Deripaska, who formerly worked with Manafort, and Viktor Vekselberg, who was at Trump's inauguration.",
          "link": "https://home.treasury.gov/news/press-releases/sm0338",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "4/17/2018 12:00:00 AM",
        "details": {
          "description": "Senate Leader Mitch McConnell says he will not allow a floor vote on a bill to protect special counsel Mueller.",
          "link": "https://www.theguardian.com/us-news/2018/apr/17/mitch-mcconnell-robert-mueller-donald-trump-firing-bill",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "5/30/2018 12:00:00 AM",
        "details": {
          "description": "Trump tweets he wished he had picked someone other than Sessions as attorney general.",
          "link": "https://twitter.com/realDonaldTrump/status/1001807216297627648?tfw_site=NPR&amp;ref_src=twsrc%5Etfw&amp;ref_url=https%3A%2F%2Fwww.npr.org%2F2018%2F05%2F30%2F615435491%2Ftrump-i-wish-i-did-pick-a-different-attorney-general-than-sessions",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      },
      {
        "date": "6/4/2018 12:00:00 AM",
        "details": {
          "description": "Trump tweets about Sessions again, blaming him for the continuing Russia investigation. \"I would have quickly picked someone else,\" Trump says.",
          "link": "https://twitter.com/realDonaldTrump/status/1003962584352030720",
          "dateDescription": "",
          "headline": null,
          "mediaOutlet": null
        }
      }
    ]
  }
]