USE TrumpRussia
GO

EXEC DropTable 'StoryTerm'
GO
EXEC DropTable 'Term'
GO
EXEC DropTable 'TermType'
GO

EXEC DropTable 'StoryTermType'
GO


CREATE TABLE TermType (
	ID int IDENTITY(1,1) NOT NULL,
	Name varchar(100) NOT NULL,
	Code varchar(20) NOT NULL,
 CONSTRAINT PK_TermType PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE Term (
	ID int IDENTITY(1,1) NOT NULL,
	Name varchar(100) NOT NULL,
	TermTypeID int NOT NULL REFERENCES TermType(ID)
 CONSTRAINT PK_Term PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE StoryTerm (
	ID int IDENTITY(1,1) NOT NULL,
	StoryID int NOT NULL REFERENCES Story(ID),
	TermID int NOT NULL REFERENCES Term(ID),
	Count int NOT NULL
 CONSTRAINT PK_StoryTerm PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE StoryTermType (
	ID int IDENTITY(1,1) NOT NULL,
	StoryID int NOT NULL REFERENCES Story(ID),
	Term varchar(max) NOT NULL DEFAULT '',
	Type varchar(20) NOT NULL DEFAULT ''
 CONSTRAINT PK_StoryTermType PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




