USE TrumpRussia
GO


EXEC  DropTable 'StoryPerson'
GO
EXEC  DropTable 'StoryOrganization'
GO
EXEC  DropTable 'StoryLocation'
GO
EXEC DropTable 'Person'
GO
EXEC DropTable 'Organization'
GO
EXEC DropTable 'Location'
GO
EXEC DropTable 'Country'
GO
EXEC DropTable 'StoryTermType'
GO
EXEC DropTable 'TermType'
GO
EXEC DropTable 'Country'
GO


CREATE TABLE StoryTermType (
	ID int IDENTITY(1,1) NOT NULL,
	StoryID int NOT NULL REFERENCES Story(ID),
	TagID int NOT NULL REFERENCES Tag(ID),
	Term varchar(200) NOT NULL DEFAULT '',
 CONSTRAINT PK_StoryTermType PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


CREATE TABLE Country (
	ID int IDENTITY(1,1) NOT NULL,
	Name varchar(100) NOT NULL
 CONSTRAINT PK_Country PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
ALTER TABLE Country ADD CONSTRAINT U_Country_Name UNIQUE(Name)
GO


CREATE TABLE Person (
	ID int IDENTITY(1,1) NOT NULL,
	CountryID int REFERENCES Country(ID),
	FirstName varchar(100) NOT NULL,
	LastName varchar(100) NOT NULL,
	Suffix varchar(100) NOT NULL
 CONSTRAINT PK_Person PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
ALTER TABLE Person ADD CONSTRAINT U_Person_FullName UNIQUE(FirstName, LastName, Suffix)
GO


CREATE TABLE StoryPerson (
	ID int IDENTITY(1,1) NOT NULL,
	StoryID int REFERENCES Story(ID),
	PersonID int REFERENCES Person(ID),
	COUNT int NOT NULL
 CONSTRAINT PK_StoryPerson PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
ALTER TABLE StoryPerson ADD CONSTRAINT U_StoryPerson_StoryPerson UNIQUE(StoryID, PersonID)
GO

CREATE TABLE Organization (
	ID int IDENTITY(1,1) NOT NULL,
	CountryID int REFERENCES Country(ID),
	Name varchar(100) NOT NULL
 CONSTRAINT PK_Organization PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
ALTER TABLE Organization ADD CONSTRAINT U_Organization_Name UNIQUE(Name)
GO

CREATE TABLE StoryOrganization (
	ID int IDENTITY(1,1) NOT NULL,
	StoryID int REFERENCES Story(ID),
	OrganizationID int REFERENCES Organization(ID),
	COUNT int NOT NULL
 CONSTRAINT PK_StoryOrganization PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
ALTER TABLE StoryOrganization ADD CONSTRAINT U_StoryOrganization_StoryOrganization UNIQUE(StoryID, OrganizationID)
GO


CREATE TABLE Location (
	ID int IDENTITY(1,1) NOT NULL,
	CountryID int REFERENCES Country(ID),
	Name varchar(100) NOT NULL
 CONSTRAINT PK_Location PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
ALTER TABLE Location ADD CONSTRAINT U_Location_Name UNIQUE(Name)
GO



CREATE TABLE StoryLocation (
	ID int IDENTITY(1,1) NOT NULL,
	StoryID int REFERENCES Story(ID),
	LocationID int REFERENCES Location(ID),
	COUNT int NOT NULL
 CONSTRAINT PK_StoryLocation PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO 
ALTER TABLE StoryLocation ADD CONSTRAINT U_StoryLocation_StoryLocation UNIQUE(StoryID, LocationID)
GO
